<?php


namespace app\controllers;

use app\models\Matrix;
use yii\rest\Controller;

class MatrixController extends Controller
{

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
    //   Matrix::getDb()->cache();
       // return Matrix::batchInsertOrUpdate([]);
        return Matrix::getMatrixAsArray();
    }

    public function actionUpdate()
    {
        $updateRecords =  \Yii::$app->getRequest()->getBodyParams();

        Matrix::batchInsertOrUpdate($updateRecords);
    }

}